# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'vistaBjjPEk.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PyQt5 import QtCore
from PyQt5 import QtWidgets
from PyQt5 import QtGui
from PyQt5.QtCore import QCoreApplication, QMetaObject, QRect
from PyQt5.QtGui import QBrush, QColor, QFont, QPalette, QPixmap, Qt
from PyQt5.QtWidgets import QFrame, QGraphicsView, QLabel, QMenu, QMenuBar, QPushButton, QStatusBar



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(513, 883)
        palette = QPalette()
        brush = QBrush(QColor(0, 0, 0, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush)
        brush1 = QBrush(QColor(240, 240, 240, 255))
        brush1.setStyle(QtGui.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        MainWindow.setPalette(palette)
        self.centralwidget = QtWidgets(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.sol = QLabel(self.centralwidget)
        self.sol.setObjectName(u"sol")
        self.sol.setGeometry(QRect(300, 590, 261, 311))
        self.sol.setPixmap(QPixmap(u"../../Pictures/solesote.png"))
        self.pla4 = QLabel(self.centralwidget)
        self.pla4.setObjectName(u"pla4")
        self.pla4.setGeometry(QRect(10, 390, 71, 61))
        self.pla4.setPixmap(QPixmap(u"venus pero este es marte.png"))
        self.pla6 = QLabel(self.centralwidget)
        self.pla6.setObjectName(u"pla6")
        self.pla6.setGeometry(QRect(10, 240, 71, 51))
        self.pla6.setPixmap(QPixmap(u"saturno.png"))
        self.pla5 = QLabel(self.centralwidget)
        self.pla5.setObjectName(u"pla5")
        self.pla5.setGeometry(QRect(10, 320, 71, 51))
        self.pla5.setPixmap(QPixmap(u"Jupiter.png"))
        self.pla8 = QLabel(self.centralwidget)
        self.pla8.setObjectName(u"pla8")
        self.pla8.setGeometry(QRect(10, 90, 71, 51))
        self.pla8.setPixmap(QPixmap(u"neptuno.png"))
        self.pla3 = QLabel(self.centralwidget)
        self.pla3.setObjectName(u"pla3")
        self.pla3.setGeometry(QRect(0, 470, 81, 81))
        self.pla3.setPixmap(QPixmap(u"../../Pictures/tierra.png"))
        self.pla2 = QLabel(self.centralwidget)
        self.pla2.setObjectName(u"pla2")
        self.pla2.setGeometry(QRect(10, 560, 71, 71))
        self.pla2.setPixmap(QPixmap(u"marte.png"))
        self.pla7 = QLabel(self.centralwidget)
        self.pla7.setObjectName(u"pla7")
        self.pla7.setGeometry(QRect(10, 150, 71, 61))
        self.pla7.setPixmap(QPixmap(u"Urano.png"))
        self.pla1 = QLabel(self.centralwidget)
        self.pla1.setObjectName(u"pla1")
        self.pla1.setGeometry(QRect(10, 660, 71, 81))
        self.pla1.setPixmap(QPixmap(u"mercurio.png"))
        self.botonIniciar = QPushButton(self.centralwidget)
        self.botonIniciar.setObjectName(u"botonIniciar")
        self.botonIniciar.setGeometry(QRect(10, 780, 61, 51))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 740, 47, 13))
        self.label.setAutoFillBackground(False)
        self.label.setScaledContents(False)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(30, 630, 47, 13))
        self.label_2.setAutoFillBackground(False)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 540, 47, 13))
        self.label_3.setAutoFillBackground(False)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 440, 47, 13))
        self.label_4.setAutoFillBackground(False)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(20, 360, 47, 13))
        self.label_5.setAutoFillBackground(False)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 280, 47, 13))
        self.label_6.setAutoFillBackground(False)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(20, 200, 47, 13))
        self.label_7.setAutoFillBackground(False)
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(20, 130, 47, 13))
        self.label_8.setAutoFillBackground(False)
        self.graphicsView = QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName(u"graphicsView")
        self.graphicsView.setGeometry(QRect(0, 0, 511, 841))
        palette1 = QPalette()
        brush2 = QBrush(QColor(255, 255, 255, 255))
        brush2.setStyle(QtCore.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        self.graphicsView.setPalette(palette1)
        self.graphicsView.setAutoFillBackground(False)
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(70, 80, 20, 691))
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(110, 10, 321, 51))
        font = QFont()
        font.setFamily(u"Segoe Script")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_neptuno = QLabel(self.centralwidget)
        self.label_neptuno.setObjectName(u"label_neptuno")
        self.label_neptuno.setGeometry(QRect(210, 90, 131, 21))
        font1 = QFont()
        font1.setFamily(u"Tw Cen MT Condensed Extra Bold")
        font1.setPointSize(16)
        self.label_neptuno.setFont(font1)
        self.label_urano = QLabel(self.centralwidget)
        self.label_urano.setObjectName(u"label_urano")
        self.label_urano.setGeometry(QRect(210, 170, 131, 21))
        self.label_urano.setFont(font1)
        self.label_saturno = QLabel(self.centralwidget)
        self.label_saturno.setObjectName(u"label_saturno")
        self.label_saturno.setGeometry(QRect(210, 240, 131, 21))
        self.label_saturno.setFont(font1)
        self.label_jupiter = QLabel(self.centralwidget)
        self.label_jupiter.setObjectName(u"label_jupiter")
        self.label_jupiter.setGeometry(QRect(210, 320, 131, 21))
        self.label_jupiter.setFont(font1)
        self.label_marte = QLabel(self.centralwidget)
        self.label_marte.setObjectName(u"label_marte")
        self.label_marte.setGeometry(QRect(210, 400, 131, 21))
        self.label_marte.setFont(font1)
        self.label_tierra = QLabel(self.centralwidget)
        self.label_tierra.setObjectName(u"label_tierra")
        self.label_tierra.setGeometry(QRect(210, 490, 131, 21))
        self.label_tierra.setFont(font1)
        self.label_venus = QLabel(self.centralwidget)
        self.label_venus.setObjectName(u"label_venus")
        self.label_venus.setGeometry(QRect(210, 580, 131, 21))
        self.label_venus.setFont(font1)
        self.label_mercurio = QLabel(self.centralwidget)
        self.label_mercurio.setObjectName(u"label_mercurio")
        self.label_mercurio.setGeometry(QRect(210, 680, 131, 21))
        self.label_mercurio.setFont(font1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.graphicsView.raise_()
        self.sol.raise_()
        self.pla4.raise_()
        self.pla6.raise_()
        self.pla5.raise_()
        self.pla8.raise_()
        self.pla3.raise_()
        self.pla2.raise_()
        self.pla7.raise_()
        self.pla1.raise_()
        self.botonIniciar.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.line.raise_()
        self.label_9.raise_()
        self.label_neptuno.raise_()
        self.label_urano.raise_()
        self.label_saturno.raise_()
        self.label_jupiter.raise_()
        self.label_marte.raise_()
        self.label_tierra.raise_()
        self.label_venus.raise_()
        self.label_mercurio.raise_()
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 513, 21))
        self.menuPLANETAS = QMenu(self.menubar)
        self.menuPLANETAS.setObjectName(u"menuPLANETAS")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuPLANETAS.menuAction())

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.sol.setText("")
        self.pla4.setText("")
        self.pla6.setText("")
        self.pla5.setText("")
        self.pla8.setText("")
        self.pla3.setText("")
        self.pla2.setText("")
        self.pla7.setText("")
        self.pla1.setText("")
        self.botonIniciar.setText(QCoreApplication.translate("MainWindow", u"Iniciar", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Mercurio", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"venus", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Tierra", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Marte", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Jupiter", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Saturno", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Urano", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Neptuno", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Ciclo planetario", None))
        self.label_neptuno.setText(QCoreApplication.translate("MainWindow", u"uy quieto", None))
        self.label_urano.setText(QCoreApplication.translate("MainWindow", u"uy quieto", None))
        self.label_saturno.setText(QCoreApplication.translate("MainWindow", u"uy quieto", None))
        self.label_jupiter.setText(QCoreApplication.translate("MainWindow", u"uy quieto", None))
        self.label_marte.setText(QCoreApplication.translate("MainWindow", u"uy quieto", None))
        self.label_tierra.setText(QCoreApplication.translate("MainWindow", u"uy quieto", None))
        self.label_venus.setText(QCoreApplication.translate("MainWindow", u"uy quieto", None))
        self.label_mercurio.setText(QCoreApplication.translate("MainWindow", u"uy quieto", None))
        self.menuPLANETAS.setTitle(QCoreApplication.translate("MainWindow", u"PLANETAS", None))
    # retranslateUi